Blog Post: Code First Workflow Welcome
stoplightio/stoplight.io pull request #1609
Opened 2020-09-28 18:01 UTC by philsturgeon

2020-09-28 18:08 UTC, lottamus commented
Deploy preview for *stoplightio* ready!

Built with commit d852cbdd4d04b4094a33f532b9e465ead50a3059

https://deploy-preview-1609--stoplightio.netlify.app

2020-10-05 20:09 UTC, philsturgeon commented on netlify/lists/blog.yaml
> -hero:
I removed this subscribe from the header because I've never seen a subscribe box _before_ the user has had a chance to read anything.

2020-10-06 14:28 UTC, philsturgeon commented
@mnaumanali94 could you help me out with one of those excellent social images?

2020-10-06 14:49 UTC, texas-kristen commented on netlify/blog-posts/introduction-to-api-testing.md
> +title: Introduction to API Testing?
```suggestion
title: Introduction to API Testing
```

2020-10-06 14:49 UTC, texas-kristen commented on netlify/blog-posts/introduction-to-api-testing.md
>    title: What is the Meaning of API Testing? | Stoplight API Intersection
```suggestion
  title: Introduction to API Testing | Stoplight API Intersection
```

2020-10-06 14:51 UTC, texas-kristen commented on netlify/blog-posts/using-api-mocking-to-unblock-teams.md
> +path: /blog/using-api-mocking-to-unblock-teams
Also need to update the meta url in line 19

2020-10-06 14:54 UTC, texas-kristen commented on netlify/blog-posts/workflows--code-first.md
> +publishedDate: 2020-09-28
```suggestion
publishedDate: 2020-10-06
```

2020-10-06 14:56 UTC, texas-kristen commented on netlify/blog-posts/workflows--code-first.md
> +  url: https://stoplight.io/blog/api-design-first-vs-code-first/
```suggestion
  url: https://stoplight.io/blog/generate-documentation-from-code
```

2020-10-06 14:58 UTC, texas-kristen requested changes
See suggestions across files and comment on blog-posts/using-api-mocking-to-unblock-teams.md

2020-10-07 05:27 UTC, mnaumanali94 commented
> @mnaumanali94 could you help me out with one of those excellent social images?

@philsturgeon Thoughts? 

![Frame 7-4](https://user-images.githubusercontent.com/17899454/95290821-a7937c80-0887-11eb-88f5-c050840487c8.png)

2020-10-07 14:20 UTC, philsturgeon commented
@mnaumanali94 I'm trying to draw folks in with "generate API docs from code" when they might not know that that is actually the code-first workflow, then introducing that concept in the article. could the text be "Generate API Docs from Code" if that fits

2020-10-07 15:22 UTC, philsturgeon commented
@texas-kristen done! could i get a rereview?

2020-10-07 15:30 UTC, texas-kristen commented on netlify/blog-posts/workflows--code-first.md
> +  image: /images/design-first-vs-code-first.png
@philsturgeon Is this the meta image you want to use? Same for Twitter card on line 42

2020-10-07 17:21 UTC, philsturgeon commented on netlify/blog-posts/workflows--code-first.md
> +  image: /images/design-first-vs-code-first.png
I felt like using the same one made sense as its both workflows.

2020-10-07 18:38 UTC, texas-kristen approved these changes

2020-10-07 20:59 UTC, merged