chore: compress images
stoplightio/stoplight.io pull request #1611
Opened 2020-09-28 22:06 UTC by paulatulis

Per https://3.basecamp.com/3986751/buckets/8824800/todos/3013435881 I removed large images and replaced with compressed versions.

I did not compress gifs because it makes them look horrible. Maybe we can go through and decide what to do with each of them. There's only a handful.

2020-09-28 22:12 UTC, lottamus commented
Deploy preview for *stoplightio* ready!

Built with commit c785651ed428cdffbe8d5e565f9abf3eea312e7b

https://deploy-preview-1611--stoplightio.netlify.app

2020-09-29 13:45 UTC, texas-kristen commented on netlify/blog-posts/writing-documentation-when-you-arent-a-technical-writer-—-part-one.md
> +![“Nation Shudders At Large Block Of Uninterrupted Text,” photo from [The Onion](https://www.theonion.com/nation-shudders-at-large-block-of-uninterrupted-text-1819571366)](/images/the-onion.jpg)_“Nat
The other image on this page needs to be changed to heat-maps.jpg

`![Heatmaps from [Nielsen Norman Group](https://www.nngroup.com/articles/f-shaped-pattern-reading-web-content-discovered/)](/images/heat-maps.jpg)_Heatmaps from [Nielsen Norman Group](https://www.nngroup.com/articles/f-shaped-pattern-reading-web-content-discovered/)_`

2020-09-29 13:48 UTC, texas-kristen requested changes
See comment regarding heatmaps image on [https://deploy-preview-1611--stoplightio.netlify.app/blog/writing-documentation-when-you-arent-a-technical-writer-part-one-ef08a09870d1/](https://deploy-preview-1611--stoplightio.netlify.app/blog/writing-documentation-when-you-arent-a-technical-writer-part-one-ef08a09870d1/)

2020-09-29 18:14 UTC, paulatulis commented on netlify/blog-posts/writing-documentation-when-you-arent-a-technical-writer-—-part-one.md
> +![“Nation Shudders At Large Block Of Uninterrupted Text,” photo from [The Onion](https://www.theonion.com/nation-shudders-at-large-block-of-uninterrupted-text-1819571366)](/images/the-onion.jpg)_“Nat
Great eye thank you so much!

2020-09-29 18:15 UTC, paulatulis commented
> @paulatulis See comment regarding heatmaps image on https://deploy-preview-1611--stoplightio.netlify.app/blog/writing-documentation-when-you-arent-a-technical-writer-part-one-ef08a09870d1/

Thanks so much for flagging. Should be updated here:
https://github.com/stoplightio/stoplight.io/pull/1611/commits/27a107dff1c15f88b07537c76214c71568649266#diff-69391cd3e2604e996c9d64573a2eec7cR80

2020-09-29 21:14 UTC, texas-kristen approved these changes

2020-09-29 21:16 UTC, merged