Adds CTAs to design guides and updates header
stoplightio/stoplight.io pull request #1613
Opened 2020-09-29 12:01 UTC by mnaumanali94

2020-09-29 12:08 UTC, lottamus commented
Deploy preview for *stoplightio* ready!

Built with commit ecd4f01ce8a05c1eb2b84d852084dffe2b7ba2d5

https://deploy-preview-1613--stoplightio.netlify.app

2020-09-29 18:08 UTC, paulatulis requested changes

2020-09-29 18:08 UTC, paulatulis commented on netlify/subpages/api-documentation-guide.md
> +        title: Create API Documentation
This is 'Generate API Documentation' in the other two tabs. Does that matter?

2020-09-29 18:08 UTC, paulatulis commented on netlify/subpages/api-types-soap-vs-rest.md
> +        href: 'https://stoplight.io/'
Is this the correct link?

2020-09-29 18:08 UTC, paulatulis commented on netlify/subpages/api-types.md
> +        href: 'https://stoplight.io/'
Is this the correct link?

2020-09-29 18:08 UTC, paulatulis commented on netlify/subpages/microservices-guide.md
> +        href: 'https://stoplight.io/'
Is this the correct link?

2020-09-29 18:11 UTC, paulatulis commented
Looks good to me! Called out a few things that I am not sure about, but you know better than me most of the time, so if they are correct, you can just disregard. 

Also, I like that these are called out, but there's a lot of whitespace. The two open source tiles have more going on, so it's not as bare. Is there a way we can set it up similarly? What do you think? 
![Screen Shot 2020-09-29 at 12 53 36 PM](https://user-images.githubusercontent.com/47359669/94598815-2881c100-0255-11eb-85c2-7615d8a2c92e.png)

2020-09-30 14:06 UTC, paulatulis reviewed
All of the CTAs look good to me! Still curious what your thoughts are on the new dropdown menu whitespace. I think it looks a bit awkward.

2020-09-30 14:39 UTC, mnaumanali94 commented
> All of the CTAs look good to me! Still curious what your thoughts are on the new dropdown menu whitespace. I think it looks a bit awkward.

Good catch. Reduced the padding.

2020-09-30 21:00 UTC, paulatulis approved these changes

2020-09-30 21:01 UTC, merged