add recurring webinar cards
stoplightio/stoplight.io pull request #1647
Opened 2020-11-04 18:24 UTC by texas-kristen

2020-11-04 18:30 UTC, lottamus commented
Deploy preview for *stoplightio* ready!

Built with commit 6036b8aaa0be74397987cf6f9590bd45fad29ebb

https://deploy-preview-1647--stoplightio.netlify.app

2020-11-11 20:23 UTC, paulatulis requested changes
Looks amazing! Just a few small things/questions.

2020-11-11 20:23 UTC, paulatulis commented on netlify/case-studies/platform-101-workshop-nov-3.md
> +<!-- ---
Should this be commented out?

2020-11-11 20:23 UTC, paulatulis commented on netlify/demo-form/request-demo.yaml
> +      - name: Technical Architect
I believe we got approval to use this quote and say it's from Amadeus - may need to run by Scott.

2020-11-11 20:23 UTC, paulatulis commented on netlify/forms/subscribe-to-stoplight-webinars.yaml
> +# hero:
Unless we'll use commented out code soon in future, can go ahead and remove

2020-11-11 20:23 UTC, paulatulis commented on netlify/settings.yaml
> +    streetAddress: 1412 Collier St, Suite C
:)

2020-11-11 20:23 UTC, paulatulis commented on netlify/case-studies/api-insights-series.md
> +    text: "Register for an API Inights Webinar Session"
```suggestion
    text: "Register for an API Insights Webinar Session"
```

2020-11-11 20:34 UTC, texas-kristen commented on netlify/case-studies/platform-101-workshop-nov-3.md
> +<!-- ---
Yeah, I don't have the recording ready to post and I'd rather not have the page live until I do, but eventually, it will go live

2020-11-11 21:09 UTC, paulatulis approved these changes

2020-11-11 21:15 UTC, merged