november-content-optimizations
stoplightio/stoplight.io pull request #1665
Opened 2020-11-30 22:19 UTC by texas-kristen

SEO updates for Callum

2020-11-30 22:32 UTC, lottamus commented
Deploy preview for *stoplightio* ready!

Built with commit 11cf5d9d484c3d7873356f26de3daaf6f420e92a

https://deploy-preview-1665--stoplightio.netlify.app

2020-12-01 17:31 UTC, paulatulis requested changes

2020-12-01 17:31 UTC, paulatulis commented on netlify/subpages/api-documentation-guide.md
> +you’ll want for the comprehensive coverage developers require. We will also cover the basics of the commonly question ‘what is API documentation’ in detail. This will also include exploring what you
```suggestion
you’ll want for the comprehensive coverage developers require. We will also cover the basics of the commonly asked question ‘what is API documentation’ in detail. This will also include exploring what you will need in
```

2020-12-03 17:40 UTC, paulatulis approved these changes

2020-12-03 17:53 UTC, merged